### PR TITLE
39 - Fix schema alignment and defaulting for the 'course' field

### LINKED ISSUE #49: Schema issue: Column 'course' has default 'NULL', expected '0' (I)
Issue when checking db schema, which probably happened post-upgrade

Detected on Moodle 3.9
```
local_recompletion_qr

column 'course' has default 'NULL', expected '0' (I)
```

### PR DESCRIPTION
**Pull request by keevan**
Closes #49

- QR set to have a default value in install.xml but was not set to have
  the same default in upgrade.php. This patch fixes that issue.

```
local_recompletion_qr

column 'course' has default 'NULL', expected '0' (I)
```

### CODE REVIEW

File: db/upgrade.php [hunk 1]
```diff
@@ -401,7 +401,6 @@ function xmldb_local_recompletion_upgrade($oldversion) {
         $table->add_field('complete', XMLDB_TYPE_CHAR, '1', null, XMLDB_NOTNULL, null, 'n');
         $table->add_field('grade', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, '0');
         $table->add_field('userid', XMLDB_TYPE_INTEGER, '10', null, null, null, null);
-        $table->add_field('course', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null);
```
Comment (danmarsden) [inline db/upgrade.php:404]: please don't modify previous upgrade blocks to remove a field - this should stay here.

File: db/upgrade.php [hunk 2]
```diff
@@ -558,5 +557,23 @@ function xmldb_local_recompletion_upgrade($oldversion) {
         upgrade_plugin_savepoint(true, 2021091500, 'local', 'recompletion');
     }
 
+    if ($oldversion < 2021100101) {
+        // Define table local_recompletion_qr to be created.
+        $table = new xmldb_table('local_recompletion_qr');
+        $field = new xmldb_field('course', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, '0', 'userid');
+        if (!$dbman->field_exists($table, $field)) {
```
Comment (danmarsden) [inline db/upgrade.php]: Can you please minimise this to the individual issue you found with the default value? - precision etc shouldn't need to change.

**Comment by danmarsden** [comment]
Thanks @keevan - I've made a few comments on your PR - hopefully you will be able to tidy that up a bit!

File: db/upgrade.php (hunk 1 above)
Comment (keevan) [reply db/upgrade.php:404]: No worries, was just trying to avoid doing an `add + change` for all future changes. I'll revert this change.

Comment (danmarsden) [reply db/upgrade.php:404]: You could look at fixing the default value in that line to prevent new installs ending up with an issue rather than removing the line, but we'd still need the upgrade step later to deal with existing installs anyway.

Comment (keevan) [reply db/upgrade.php:404]: It is a sound suggestion, I've added that. Who knows, maybe Moodle can be smart about it later on and do a no-op for the defaulting if it's already correct.

File: db/upgrade.php (hunk 2 above)
Comment (keevan) [reply db/upgrade.php]: I've updated this to just apply the expected default. The field was never 'missing' so I've removed the surrounding conditions as well.

**Comment by keevan** [comment]
Thanks for your feedback @danmarsden , could you please give it another look.
